### ISSUE TITLE
setup.py fails

### ISSUE THREAD

**Issue by bomzj** [day0market/support_resistance#10]
Running the following on Windows `python setup.py install` fails

<details><summary>Details</summary>
<p>

C:\Projects\support_resistance>python setup.py install
C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\__init__.py:81: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
running install
C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
creating pricelevels.egg-info
writing pricelevels.egg-info\PKG-INFO
writing dependency_links to pricelevels.egg-info\dependency_links.txt
writing requirements to pricelevels.egg-info\requires.txt
writing top-level names to pricelevels.egg-info\top_level.txt
writing manifest file 'pricelevels.egg-info\SOURCES.txt'
reading manifest file 'pricelevels.egg-info\SOURCES.txt'
writing manifest file 'pricelevels.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib
creating build\lib\pricelevels
copying pricelevels\cluster.py -> build\lib\pricelevels
copying pricelevels\exceptions.py -> build\lib\pricelevels
copying pricelevels\version.py -> build\lib\pricelevels
copying pricelevels\_abstract.py -> build\lib\pricelevels
copying pricelevels\__init__.py -> build\lib\pricelevels
creating build\lib\pricelevels\scoring
copying pricelevels\scoring\abstract.py -> build\lib\pricelevels\scoring
copying pricelevels\scoring\touch_scorer.py -> build\lib\pricelevels\scoring
copying pricelevels\scoring\__init__.py -> build\lib\pricelevels\scoring
creating build\lib\pricelevels\visualization
copying pricelevels\visualization\levels_on_candlestick.py -> build\lib\pricelevels\visualization
copying pricelevels\visualization\levels_with_zigzag.py -> build\lib\pricelevels\visualization
copying pricelevels\visualization\_helpers.py -> build\lib\pricelevels\visualization
copying pricelevels\visualization\__init__.py -> build\lib\pricelevels\visualization
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\pricelevels
copying build\lib\pricelevels\cluster.py -> build\bdist.win-amd64\egg\pricelevels
copying build\lib\pricelevels\exceptions.py -> build\bdist.win-amd64\egg\pricelevels
creating build\bdist.win-amd64\egg\pricelevels\scoring
copying build\lib\pricelevels\scoring\abstract.py -> build\bdist.win-amd64\egg\pricelevels\scoring
copying build\lib\pricelevels\scoring\touch_scorer.py -> build\bdist.win-amd64\egg\pricelevels\scoring
copying build\lib\pricelevels\scoring\__init__.py -> build\bdist.win-amd64\egg\pricelevels\scoring
copying build\lib\pricelevels\version.py -> build\bdist.win-amd64\egg\pricelevels
creating build\bdist.win-amd64\egg\pricelevels\visualization
copying build\lib\pricelevels\visualization\levels_on_candlestick.py -> build\bdist.win-amd64\egg\pricelevels\visualization
copying build\lib\pricelevels\visualization\levels_with_zigzag.py -> build\bdist.win-amd64\egg\pricelevels\visualization
copying build\lib\pricelevels\visualization\_helpers.py -> build\bdist.win-amd64\egg\pricelevels\visualization
copying build\lib\pricelevels\visualization\__init__.py -> build\bdist.win-amd64\egg\pricelevels\visualization
copying build\lib\pricelevels\_abstract.py -> build\bdist.win-amd64\egg\pricelevels
copying build\lib\pricelevels\__init__.py -> build\bdist.win-amd64\egg\pricelevels
byte-compiling build\bdist.win-amd64\egg\pricelevels\cluster.py to cluster.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\pricelevels\exceptions.py to exceptions.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\pricelevels\scoring\abstract.py to abstract.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\pricelevels\scoring\touch_scorer.py to touch_scorer.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\pricelevels\scoring\__init__.py to __init__.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\pricelevels\version.py to version.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\pricelevels\visualization\levels_on_candlestick.py to levels_on_candlestick.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\pricelevels\visualization\levels_with_zigzag.py to levels_with_zigzag.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\pricelevels\visualization\_helpers.py to _helpers.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\pricelevels\visualization\__init__.py to __init__.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\pricelevels\_abstract.py to _abstract.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\pricelevels\__init__.py to __init__.cpython-312.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying pricelevels.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying pricelevels.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pricelevels.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pricelevels.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
copying pricelevels.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pricelevels.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
creating dist
creating 'dist\pricelevels-0.0.2-py3.12.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing pricelevels-0.0.2-py3.12.egg
creating c:\users\maksi\appdata\local\programs\python\python312\lib\site-packages\pricelevels-0.0.2-py3.12.egg
Extracting pricelevels-0.0.2-py3.12.egg to c:\users\maksi\appdata\local\programs\python\python312\lib\site-packages
Adding pricelevels 0.0.2 to easy-install.pth file

Installed c:\users\maksi\appdata\local\programs\python\python312\lib\site-packages\pricelevels-0.0.2-py3.12.egg
Processing dependencies for pricelevels==0.0.2
Searching for matplotlib==3.1.1
Reading https://pypi.org/simple/matplotlib/
Downloading https://files.pythonhosted.org/packages/12/d1/7b12cd79c791348cb0c78ce6e7d16bd72992f13c9f1e8e43d2725a6d8adf/matplotlib-3.1.1.tar.gz#sha256=1febd22afe1489b13c6749ea059d392c03261b2950d1d45c17e3aed812080c93
Best match: matplotlib 3.1.1
Processing matplotlib-3.1.1.tar.gz
Writing C:\Users\maksi\AppData\Local\Temp\easy_install-ad62dqj5\matplotlib-3.1.1\setup.cfg
Running matplotlib-3.1.1\setup.py -q bdist_egg --dist-dir C:\Users\maksi\AppData\Local\Temp\easy_install-ad62dqj5\matplotlib-3.1.1\egg-dist-tmp-6pny9kd4
Traceback (most recent call last):
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 157, in save_modules
    yield saved
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 199, in setup_context
    yield
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 260, in run_setup
    _execfile(setup_script, ns)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "C:\Users\maksi\AppData\Local\Temp\easy_install-ad62dqj5\matplotlib-3.1.1\setup.py", line 51, in <module>
  File "C:\Users\maksi\AppData\Local\Temp\easy_install-ad62dqj5\matplotlib-3.1.1\versioneer.py", line 1410, in get_version
  File "C:\Users\maksi\AppData\Local\Temp\easy_install-ad62dqj5\matplotlib-3.1.1\versioneer.py", line 1344, in get_versions
  File "C:\Users\maksi\AppData\Local\Temp\easy_install-ad62dqj5\matplotlib-3.1.1\versioneer.py", line 401, in get_config_from_root
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\support_resistance\setup.py", line 11, in <module>
    setup(
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\dist.py", line 967, in run_command
    super().run_command(command)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\install.py", line 87, in run
    self.do_egg_install()
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\install.py", line 148, in do_egg_install
    cmd.run(show_deprecation=False)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\easy_install.py", line 437, in run
    self.easy_install(spec, not self.no_deps)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\easy_install.py", line 686, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\easy_install.py", line 736, in install_item
    self.process_distribution(spec, dist, deps)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\easy_install.py", line 785, in process_distribution
    distros = WorkingSet([]).resolve(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\pkg_resources\__init__.py", line 798, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\pkg_resources\__init__.py", line 834, in _resolve_dist
    dist = best[req.key] = env.best_match(
                           ^^^^^^^^^^^^^^^
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\pkg_resources\__init__.py", line 1104, in best_match
    return self.obtain(req, installer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\pkg_resources\__init__.py", line 1115, in obtain
    return installer(requirement) if installer else None
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\easy_install.py", line 709, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\easy_install.py", line 734, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\easy_install.py", line 929, in install_eggs
    return self.build_and_install(setup_script, setup_base)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\easy_install.py", line 1203, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\easy_install.py", line 1189, in run_setup
    run_setup(setup_script, args)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
    with setup_context(setup_dir):
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 191, in setup_context
    with save_modules():
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 170, in save_modules
    saved_exc.resume()
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 144, in resume
    raise exc.with_traceback(self._tb)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 157, in save_modules
    yield saved
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 199, in setup_context
    yield
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 260, in run_setup
    _execfile(setup_script, ns)
  File "C:\Users\maksi\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "C:\Users\maksi\AppData\Local\Temp\easy_install-ad62dqj5\matplotlib-3.1.1\setup.py", line 51, in <module>
  File "C:\Users\maksi\AppData\Local\Temp\easy_install-ad62dqj5\matplotlib-3.1.1\versioneer.py", line 1410, in get_version
  File "C:\Users\maksi\AppData\Local\Temp\easy_install-ad62dqj5\matplotlib-3.1.1\versioneer.py", line 1344, in get_versions
  File "C:\Users\maksi\AppData\Local\Temp\easy_install-ad62dqj5\matplotlib-3.1.1\versioneer.py", line 401, in get_config_from_root
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'

</p>
</details>

**Comment by bomzj** [comment]
After back and forth with ChatGpt, we managed to fix all errors with installation :). Had to update required packages to newer version in `setup.py` to be compatible with my python 3.12 version and install some missing stuff like Cython...

**Comment by DOGEfind** [comment]
What have you improved? I have the same mistake.
